version: '3.8'

services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/vendor:/var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    image: node:16
    container_name: vue_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install &&
             npm run serve"
    depends_on:
      - app

volumes:
  db_data:
